on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "imagine-tai-tokerau"
  AZURE_WEBAPP_PACKAGE_PATH: "build"
  NODE_VERSION: "12.x"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: yarn install
        run: |
          yarn install
      - name: yarn build
        run: |
          yarn build
      - name: Deploy to azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PORTAL_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
